# Generated by Django 6.1 on 2026-09-17 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional label used as image alt text or video caption.', max_length=120)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=5)),
                ('placement', models.CharField(choices=[('hero', 'Hero banner'), ('gallery', 'Inside the Studio')], default='gallery', help_text='Where this media appears on the homepage.', max_length=7)),
                ('image', models.ImageField(blank=True, help_text='Required when media type is Photo.', null=True, upload_to='gallery/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('video', models.FileField(blank=True, help_text='Required when media type is Video.', null=True, upload_to='gallery/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])])),
                ('order', models.PositiveIntegerField(default=1, help_text='Studio gallery position: 1 to 7. Ignored for the hero.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to hide the item from the public website.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['placement', 'order', '-uploaded_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('placement', 'gallery')), fields=('placement', 'order'), name='unique_gallery_slot')],
            },
        ),
    ]
