# Generated by Django 6.1.1 on 2026-09-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional label, e.g. 'Pull-up rig' — used as alt text / caption.",
                        max_length=120,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")],
                        default="photo",
                        max_length=5,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Required for photo items.",
                        null=True,
                        upload_to="gallery/photos/",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Required for video items. MP4/WebM recommended.",
                        null=True,
                        upload_to="gallery/videos/",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first. Photo slots 1-7 map to the homepage grid in this order.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide from the website without deleting it.",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-uploaded_at"],
            },
        ),
    ]
