# Generated by Django 6.1 on 2026-09-17 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='galleryitem',
            name='unique_gallery_slot',
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Required for Photo items. JPG, JPEG, PNG or WebP. Maximum 5 MB.', null=True, upload_to='gallery/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Studio gallery position: 1 to 7. Used for gallery photos only. Ignored for the hero banner and videos.'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='video',
            field=models.FileField(blank=True, help_text='Required for Video items. MP4, WebM or MOV. Maximum 50 MB.', null=True, upload_to='gallery/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])]),
        ),
        migrations.AddConstraint(
            model_name='galleryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('media_type', 'photo'), ('placement', 'gallery')), fields=('placement', 'order'), name='unique_gallery_photo_slot'),
        ),
    ]
