# Generated by Django 6.1.1 on 2026-09-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galleryitem",
            options={"ordering": ["placement", "order", "-uploaded_at"]},
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="placement",
            field=models.CharField(
                choices=[
                    ("hero", "Hero banner (top of homepage)"),
                    ("gallery", "Inside the Studio gallery"),
                ],
                default="gallery",
                help_text="Where on the homepage this appears.",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Gallery items only: 1-7, matching the numbered grid positions. Ignored for the hero banner.",
            ),
        ),
    ]
